import type { Metadata } from "next";
import localFont from "next/font/local";
import NavMenu from "./components/menuBar/NavMenu";
import Script from "next/script";
import Head from "next/head";
import "bootstrap/dist/css/bootstrap.min.css"
// import "bootstrap/dist/js/bootstrap.bundle"
import "./globals.css";
import '@fortawesome/fontawesome-free/css/all.min.css';
import MobileMenu from "./components/menuBar/MobileMenu";




const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

<Head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossOrigin="anonymous" referrerPolicy="no-referrer" />


        </Head>
      <body>
        
      <section className="d-flex">

        <NavMenu />


        <div className="main-content">
          <MobileMenu />
 
  
        {children}

      
      </div>

        </section>
        <Script
          src="https://code.jquery.com/jquery-3.6.0.min.js"
          strategy="beforeInteractive"
        />

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" />

        <Script
        id="custom-jquery-script"
        dangerouslySetInnerHTML={{
          __html: `
            (function ($) {
              "use strict";
              $(window).on("load", function () {
                // PreLoader Init
                function preLoader() {
                  $("body").addClass("loaded");
                  $(".preloader-wrapper").addClass("loaded");
                }
                preLoader();
              });
              $(document).ready(function () {
                // navbarToggle Init
                function navbarToggle() {
                  $(".nav-toggle").on("click", function () {
                    $(".sidenav").toggleClass("show");
                    $(".nav-toggle span").toggleClass("fa-times fa-bars");
                    $(".nav-toggle-overlay").toggleClass("show");
                  });
                  $(".nav-toggle-overlay").on("click", function () {
                    $(".sidenav").removeClass("show");
                    $(".nav-toggle span").toggleClass("fa-bars fa-times");
                    $(".nav-toggle-overlay").removeClass("show");
                  });
                }
                navbarToggle();
                
                // form validation (only for this page)
                window.addEventListener(
                  "load",
                  function () {
                    var forms = document.getElementsByClassName("needs-validation");
                    var validation = Array.prototype.filter.call(forms, function (form) {
                      form.addEventListener(
                        "submit",
                        function (event) {
                          if (form.checkValidity() === false) {
                            event.preventDefault();
                            event.stopPropagation();
                          }
                          form.classList.add("was-validated");
                        },
                        false
                      );
                    });
                  },
                  false
                );
              });
            })(jQuery);
          `,
        }}
      />




      </body>
    </html>
  );
}
